version: '3.1'

services:

  app:
    image: openjdk:13-jdk-alpine
    container_name: yamanager_app
    volumes:
      - /tmp
      - ./server/target/ymanager-1.0-SNAPSHOT-full-app.jar:/app.jar
    entrypoint: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Djava.security.egd=file:/dev/./urandom -jar /app.jar
    restart: always
    ports:
      - 9080:8080
      - 6005:5005
    depends_on:
      - db
    links:
      - db

  db:
    image: mariadb
    container_name: yamanager_db
    restart: always
    volumes:
      - ./server/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
      MYSQL_DATABASE: yamanager
    ports:
      - 3306:3306