FROM maven:3.6-jdk-11

ARG BUILD_DIR=/app

WORKDIR $BUILD_DIR

#fetch dependencies and cache them, this will run only of pom.xml changes
COPY pom.xml .
RUN mvn install

# do the actual build
COPY src/ src/
RUN mvn clean install \
    && cp target/*.jar /app.jar